import React from 'react'
import Navbar from '../Components/Navbar'
import Card from '../Components/Card'

function Tips() {
  return (
    <div className='main-main'>
      <Navbar/>
      <div className='tip-main'>
        <p className='tip-p'>Ensuring good health during pregnancy is crucial for both the mother and the growing baby. Taking care of oneself and adopting healthy habits can greatly contribute to a smooth and enjoyable pregnancy journey. Here are some starting points to consider when it comes to maintaining your well-being:</p>
        <h3>11 Tips for a Healthy Pregnancy</h3>
        <Card  head = '1.) Take a Prenatal Vitamin' img = '/img/vitamins.webp' text = "Taking prenatal vitamins as soon as you confirm your pregnancy is a wise decision. In fact, it's often recommended to start taking them even before conception if you're trying to get pregnant. This is because crucial development, such as the formation of the neural tube, occurs within the first month of pregnancy. By taking prenatal vitamins early on, you ensure that your body receives essential nutrients like folate, calcium, and iron from the beginning.You can find prenatal vitamins over the counter at most drug stores, or your doctor can prescribe them for you. If you experience queasiness when taking them, you can try taking them at night or with a light snack. Chewing gum or sucking on hard candy afterward may also alleviate any discomfort you may feel."/>



      <Card head ='2.) Do pregnancy exercise' img ='/img/exercise.webp' text="Maintaining an active lifestyle during pregnancy is crucial for your overall well-being. Regular exercise can help reduce stress, improve circulation, enhance mood, and promote better sleep. Engaging in activities like pregnancy exercise classes or walking for at least 15 to 20 minutes a day at a moderate pace, preferably in cool, shaded areas or indoors to avoid overheating, can be beneficial.Pilates, yoga, swimming, and walking are generally safe and effective exercises for most pregnant individuals. However, it is essential to consult with your doctor before starting any exercise program to ensure it aligns with your specific needs and health conditions. Aim for approximately 30 minutes of exercise on most days of the week. Pay attention to your body's cues and avoid overexertion. It's important to strike a balance and listen to what your body tells you during pregnancy."/>


      <Card head = '3.) Educate yourself for better experience' img = '/img/education.webp' text = "Attending a childbirth class, regardless of whether it's your first baby or not, can greatly contribute to your preparedness for delivery. These classes offer valuable knowledge about childbirth techniques and infant care, allowing you to ask questions and address any concerns you may have. Moreover, you'll become familiar with the facility where you'll give birth and its staff, fostering a sense of comfort and confidence.This is also an opportune time to review your family's medical history. Discuss any issues or complications you experienced in past pregnancies with your doctor. Additionally, it's important to inform your healthcare provider about any occurrences of birth defects or genetic conditions within your family. This information aids in providing you with appropriate care and support throughout your pregnancy journey."/>


      <Card head = '4.) Practice Kegels'img ='/img/kegel.jpg' text={`Kegel exercises are beneficial for strengthening the pelvic floor muscles, which provide support to the bladder, bowels, and uterus. When performed correctly, these exercises can make delivery easier and help prevent future issues with incontinence. One of the advantages of kegels is that they can be discreetly done anytime and anywhere, whether you're in the car, sitting at your desk, or waiting in line at the grocery store.
  Here's a step-by-step guide on how to do kegels correctly:


1.) Practice the sensation of stopping the flow of urine when you're using the bathroom. \n
2.) Squeeze and tighten the pelvic floor muscles as if you're halting the urine flow. \n
3.) Hold this contraction for three seconds. \n
4.) Relax the muscles for three seconds. \n
5.) Repeat this sequence ten times. \n
Regularly incorporating kegel exercises into your routine can contribute to a stronger pelvic floor and potential long-term benefits for your overall pelvic health.`}/>



      <Card head = '5.) Eliminate Toxins' img = '/img/alochol.webp' text ="To ensure the well-being of both you and your baby during pregnancy, it is crucial to avoid tobacco, alcohol, illicit drugs, and harmful substances like solvents (e.g., paint thinners and nail polish remover). These substances have been linked to birth defects, miscarriage, and various complications. Smoking cigarettes, in particular, can significantly reduce oxygen flow to your baby and increase the risk of preterm birth and other complications.If you are struggling to quit smoking, drinking, or using drugs, it is important to inform your doctor. They can provide guidance, support, and refer you to appropriate programs that can help you quit these habits. Seeking professional assistance can increase your chances of successfully overcoming these harmful behaviors and promoting a healthier pregnancy for both you and your baby."/>


      <Card head = '6.) Check Your Medications'  img='/img/medicine.jpg'       text='Before taking any over-the-counter (OTC) medications, supplements, or "natural" remedies during pregnancy, it is essential to consult with your doctor or midwife. This precaution applies to all medications, including OTC non-steroidal anti-inflammatory drugs (NSAIDs) like ibuprofen.According to the National Health Service (NHS), taking NSAIDs such as ibuprofen during pregnancy can potentially increase the risk of miscarriage and harm fetal blood vessels. To ensure the safety of both you and your baby, it is best to seek professional medical advice before taking any medication, whether it is prescribed or available over the counter. Your healthcare provider will be able to provide specific guidance and recommend safer alternatives when necessary.'/>

      <Card head = '7.) Go Shoe Shopping'  img ='/img/pregnancy-shoes.webp' text="As your pregnancy progresses, you may notice changes in your feet due to weight gain and fluid retention. These changes can include increased foot size and swelling. The shift in your center of gravity and added pressure on your feet can lead to discomfort and overpronation, which is the flattening of the feet.To alleviate these issues, it's recommended to wear comfortable and non-restrictive shoes during pregnancy. Opt for footwear that provides proper support and allows for natural movement of the feet. Additionally, taking breaks throughout the day to elevate your feet can help prevent fatigue and reduce swelling in the feet, legs, and ankles.Remember, this is a great opportunity to indulge in some shoe shopping and find footwear that keeps you comfortable and supported during your pregnancy journey."/>
      <Card head = '8.) Drink More Water' img = '/img/water.webp' text = "During pregnancy, your body undergoes significant changes to support the growth and development of your baby. One important change is an increase in blood volume to meet the demands of supplying oxygen and nutrients to your baby through the placenta, as well as removing waste products.To support this increased blood volume and maintain optimal hydration, it is essential to drink an adequate amount of water during pregnancy. Drinking water offers numerous benefits, including preventing constipation, hemorrhoids, urinary tract infections (UTIs), fatigue, headaches, swelling, and other uncomfortable pregnancy symptoms.It is generally recommended to aim for 8 to 10 glasses of water per day. If you find plain water unappealing, you can enhance its flavor by adding a squeeze of lime or a splash of fruit juice. Remember to listen to your body's signals of thirst and drink water accordingly. Staying well-hydrated is crucial for your overall well-being and the healthy development of your baby."/>

      <Card head = '9.) Eat Folate-Rich Foods' img ='/img/folate.webp' text = "In addition to maintaining proper hydration, it is important to focus on consuming a well-balanced diet during pregnancy. Including foods rich in folate is particularly important for the development of your baby's neural tube and the production of new red blood cells.To ensure an adequate intake of folate, include foods such as fortified cereals, asparagus, lentils, wheat germ, oranges, and orange juice in your diet. These foods are excellent sources of folate, which is a form of B vitamin. Folate plays a crucial role in the proper development of the baby's neural tube, which covers the spinal cord, and is essential for the formation of new red blood cells.By incorporating these folate-rich foods into your meals and maintaining a well-balanced diet overall, you can support the healthy growth and development of your baby. However, it is always advisable to consult with your healthcare provider or a registered dietitian for personalized dietary recommendations during pregnancy."/>
      <Card head ='10.)Recharge With Fruit' img = '/img/fruit.webp' text = "It is generally recommended to limit caffeine intake during pregnancy due to potential harmful effects on both you and your baby. However,reducing caffeine consumption can be challenging, especially if you're accustomed to consuming it, such as through your morning coffee routine.To help boost your energy levels without relying on caffeine, you can try nibbling on fruits like bananas and apples.These fruits contain natural sugars that can provide a quick pick-me-up and help lift your energy levels. Additionally, fruits offer essential nutrients and fiber that can contribute to your overall well-being during pregnancy.Remember, it's important to maintain a balanced and varied diet throughout your pregnancy. If you have concerns about your caffeine intake or dietary choices,it's always best to consult with your healthcare provider or a registered dietitian for personalized advice and guidance"/>
      <Card head = '11.) Know When to Call the Doctor' img='/img/doctor.webp' text = "Being pregnant can be confusing, especially if it's your first time. How do you know which twinge is normal and which one isn't? According to the Centers for Disease Control and Prevention (CDC), you should call your doctor if you have any of these symptoms: pain of any kind, strong cramps, contractions at 20-minute intervals, vaginal bleeding or leaking of fluid, dizziness or fainting, shortness of breath, heart palpitations, constant nausea and vomiting, trouble walking or edema (swelling of joints), and decreased activity by the baby. It's important to recognize these symptoms and reach out to your healthcare provider for further evaluation and guidance. Remember, your healthcare provider is the best resource to provide individualized advice and support throughout your pregnancy journey."/>
      </div>
    </div>
  )
}

export default Tips
